
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirportIS
{

using System;
    using System.Collections.Generic;
    
public partial class Airports
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Airports()
    {

        this.Flights = new HashSet<Flights>();

    }


    public int airport_code { get; set; }

    public string airport_name { get; set; }

    public string city { get; set; }

    public string coordinates { get; set; }

    public string timezone { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Flights> Flights { get; set; }

}

}
