
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirportIS
{

using System;
    using System.Collections.Generic;
    
public partial class Flights
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Flights()
    {

        this.Ticket_flights = new HashSet<Ticket_flights>();

    }


    public int flight_id { get; set; }

    public int flight_no { get; set; }

    public string scheduled_departure { get; set; }

    public string scheduled_arrival { get; set; }

    public string departure_airport { get; set; }

    public string arrival_airport { get; set; }

    public string status { get; set; }

    public int aircraft_code { get; set; }

    public string actual_departure { get; set; }

    public string actual_arrival { get; set; }

    public int airport_code { get; set; }



    public virtual Aircrafts Aircrafts { get; set; }

    public virtual Airports Airports { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ticket_flights> Ticket_flights { get; set; }

}

}
