
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirportIS
{

using System;
    using System.Collections.Generic;
    
public partial class Tickets
{

    public int ticket_no { get; set; }

    public int book_ref { get; set; }

    public int passenger_id { get; set; }

    public System.DateTime contact_data { get; set; }



    public virtual Bookings Bookings { get; set; }

    public virtual Passenger Passenger { get; set; }

    public virtual Ticket_flights Ticket_flights { get; set; }

}

}
